env:
  - GO111MODULE=on
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
-
  main: ./cmd/authwrapper
  goarch:
    - amd64
    - arm64
  goos:
    - darwin
    - linux
  env:
  - CGO_ENABLED=0
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
